<a href="https://colab.research.google.com/github/Jichack/studio/blob/main/RL_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from google.colab import drive
drive.mount('/content/drive')
!git clone https://github.com/Jichack/studio.git
%cd studio
!pip install -r requirements.txt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/studio/studio/studio/studio


In [ ]:
import numpy
import gym
print("numpy:", numpy.__version__)
print("gym:", gym.__version__)

numpy: 1.23.5
gym: 0.26.2


In [ ]:
import gym
env = gym.make('CartPole-v1')
for i in range(10):
    env.reset()
    for j in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)
        print(observation)
env.close

[-0.01615715  0.2031374  -0.04275196 -0.3494779 ]
[-0.0120944   0.3988405  -0.04974152 -0.6553295 ]
[-0.00411759  0.20444505 -0.06284811 -0.37871504]
[-2.8687957e-05  4.0040061e-01 -7.0422411e-02 -6.9053328e-01]
[ 0.00797932  0.20632288 -0.08423308 -0.42082527]
[ 0.01210578  0.40253097 -0.09264958 -0.7388292 ]
[ 0.0201564   0.20880224 -0.10742617 -0.47668242]
[ 0.02433245  0.405264   -0.11695982 -0.80119884]
[ 0.03243773  0.2119237  -0.13298379 -0.5474776 ]
[ 0.0366762   0.40863863 -0.14393334 -0.8789268 ]
[ 0.04484897  0.21573478 -0.16151188 -0.63473356]
[ 0.04916367  0.41269708 -0.17420655 -0.9736102 ]
[ 0.05741761  0.22028592 -0.19367875 -0.74031997]
[ 0.06182333  0.02829018 -0.20848516 -0.51429725]
[ 0.06238913  0.22564417 -0.2187711  -0.8647694 ]
[ 0.06690201  0.42296606 -0.23606649 -1.2175044 ]
[ 0.07536133  0.62022144 -0.26041657 -1.573942  ]
[ 0.08776577  0.4289731  -0.29189542 -1.372442  ]
[ 0.09634523  0.62632287 -0.31934425 -1.7405487 ]
[ 0.10887168  0.43592095 -0.3541552  -

/usr/local/lib/python3.11/dist-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(
/usr/local/lib/python3.11/dist-packages/gym/envs/classic_control/cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


<bound method Wrapper.close of <TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>>

In [19]:
import os
print(os.getcwd())

/content/studio


Cloning into 'studio'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), done.
/content/studio
cp: cannot stat '/content/RL_experiment.ipynb': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
remote: Permission to Jichack/studio.git denied to Jichack.
fatal: unable to access 'https://github.com/Jichack/studio.git/': The requested URL returned error: 403
