<a href="https://colab.research.google.com/github/Jichack/studio/blob/main/RL_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
!git clone https://github.com/Jichack/studio.git
%cd studio
!pip install -r requirements.txt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
fatal: destination path 'studio' already exists and is not an empty directory.
/content/studio


In [2]:
import numpy
import gym
print("numpy:", numpy.__version__)
print("gym:", gym.__version__)

numpy: 1.23.5
gym: 0.26.2


In [3]:
import gym
env = gym.make('CartPole-v1')
for i in range(10):
    env.reset()
    for j in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)
        print(observation)
env.close

/usr/local/lib/python3.11/dist-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(
/usr/local/lib/python3.11/dist-packages/gym/envs/classic_control/cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(
/usr/local/lib/python3.11/dist-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(
/usr/local/lib/python3.11/dist-packages/gym/envs/classic_control/cartpole.py:177: UserWarning: WARN: Yo

[-0.00802787 -0.19134869  0.01147474  0.34224844]
[-0.01185484 -0.386632    0.01831971  0.63852763]
[-0.01958748 -0.19177021  0.03109026  0.35166967]
[-0.02342288  0.00289613  0.03812365  0.06895034]
[-0.02336496 -0.19275106  0.03950266  0.37341353]
[-0.02721998 -0.38841125  0.04697093  0.6782856 ]
[-0.03498821 -0.5841532   0.06053664  0.98537904]
[-0.04667127 -0.78003144  0.08024422  1.2964451 ]
[-0.0622719  -0.58601516  0.10617313  1.0299237 ]
[-0.0739922  -0.78237736  0.1267716   1.3539646 ]
[-0.08963975 -0.58905405  0.15385088  1.1034778 ]
[-0.10142083 -0.39625314  0.17592044  0.86274636]
[-0.10934589 -0.59327763  0.19317538  1.205176  ]
[-0.12121145 -0.4011039   0.2172789   0.97871816]
[-0.12923352 -0.5983726   0.23685326  1.3310423 ]
[-0.14120097 -0.40688765  0.2634741   1.1208197 ]
[-0.14933872 -0.6043167   0.2858905   1.4833119 ]
[-0.16142507 -0.80156577  0.31555673  1.8500878 ]
[-0.17745638 -0.61098164  0.3525585   1.6695687 ]
[-0.18967602 -0.42122367  0.38594988  1.5039574 ]


<bound method Wrapper.close of <TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>>